base: &base
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  # NOTE must encapsulate password due to single quote usage
  password: "<%= ENV["POSTGRES_PASSWORD"] %>"

# NOTE development is specific to local development database
development:
  <<: *base
  database: <%= ENV["DATABASE_NAME"] %>_development

test: &test
  <<: *base
  database: <%= ENV["DATABASE_NAME"] %>_test

production:
  <<: *base
  database: <%= ENV["DATABASE_NAME"] %>_production

demo:
  <<: *base
  database: <%= ENV["DATABASE_NAME"] %>_demo

dev:
  <<: *base
  database: <%= ENV["DATABASE_NAME"] %>_dev